- hosts: all
#  tasks:
#    - name: "Criando um arquivo no servidor"
#      shell: "echo 'escrevendo algo no servidor' >> teste.txt"

  tasks:
    - name: Creating a file with content
      copy:
        dest: "teste2.txt"
        content: |
          bla bla
          bla bla bla
          
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes # permite rodar como sudo
        
    - name: "Instalando apache"
      apt:
        name: "apache2"
        state: latest
      become: yes # permite rodar como sudo
