- hosts: all
  tasks:
    - name: "Criando um arquivo no servidor"
      shell: "echo 'escrevendo algo no servidor' >> teste.txt"
    
    - name: "Instalando apache"
      apt:
        name: "apache2"
        state: lateste
      become: yes # permite rodar como sudo
