- hosts: all
#  tasks:
#    - name: "Criando um arquivo no servidor"
#      shell: "echo 'escrevendo algo no servidor' >> teste.txt"

  tasks:
  
#    - name: Creating a file with content
#      copy:
#        dest: "teste2.txt"
#        content: |
#          bla bla
#          bla bla bla
          
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=86400 # um dia
      become: yes # permite rodar como sudo
        
    - name: "Instalando apache"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # permite rodar como sudo
      with_items:
        - php7.4
        - apache2
        - libapache2-mod-php7.4
        - php-mysql
        - php-curl
        - mysql-server
        - python3-pycurl
        - python3-mysqldb
        - unzip
        
    - shell: mysql --version
      register: ps
    - debug:
        msg: "Verifica instalação: '{{ ps.stdout_lines }}' "
        
    - name: "Fazendo downlaod do wordpress"
      get_url:
        url: "https://br.wordpress.org/latest-pt_BR.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: "Fazendo descompactação dos arquivos do WP"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www"
        remote_src: yes
      become: yes
      
    - name: "Copia arquivo WP"
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes 
      
    - name: "Configura o wp-config com as senhas"
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'nome_do_banco_de_dados_aqui', value: 'banco_wordpress' }
        - { regex: 'nome_de_usuario_aqui', value: 'root' }
        - { regex: 'senha_aqui', value: 'root' }
      become: yes

    - shell: ls -la /var/www/wordpress
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
