- hosts: all
  handlers:
    - name: "restart nginx"
      service:
        name: nginx
        state: restarted
      become: yes

  tasks:
  
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=86400 # um dia
      become: yes # permite rodar como sudo

    - name: "Instalando nginx"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # permite rodar como sudo
      with_items:
        - nginx
        - unzip
        
    - name: "Fazendo downlaod do tema bootstrap"
      get_url:
        url: "https://github.com/startbootstrap/startbootstrap-sb-admin-2/archive/gh-pages.zip"
        dest: "/tmp/gh-pages.zip"

    - name: "Fazendo descompactação dos arquivo do bootstrap para a pasta html do nginx"
      unarchive: 
        src: "/tmp/gh-pages.zip"
        dest: "/var/www/html"
        remote_src: yes
      become: yes  
      
    - name: "Configura arquivo default do nginx"
      replace:
        path: '/etc/nginx/sites-available/default'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: '/var/www/html', value: '/var/www/html/startbootstrap-sb-admin-2-gh-pages' }
      become: yes      
      
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /var/www/html/index.nginx-debian.html
        state: absent  
      become: yes
      notify:
        - "restart nginx"      
