- hosts: all

  tasks:
  
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=86400 # um dia
      become: yes # permite rodar como sudo

    - name: "Instalando nginx"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # permite rodar como sudo
      with_items:
        - nginx
